export default {
  'loading': 'Wird geladen',

  'firstName': 'Vorname',
  'lastName': 'Nachname',
  'emailAddress': 'Emailadresse',
  'username': 'Benutzername',
  'password': 'Passwort',
  'currentPassword': 'Aktuelles Passwort',
  'newPassword': 'Neues Passwort',
  'passwordRepeat': 'Passwort wiederholen',
  'logIn': 'Anmelden',
  'logOut': 'Abmelden',
  'register': 'Registrieren',
  'save': 'Speichern',
  'cancel': 'Abbrechen',
  'close': 'Schließen',
  'yes': 'Ja',
  'no': 'Nein',

  'allItems': 'Alle',
  'unreadItems': 'Ungelesen',
  'archive': 'Archiv',
  'folder': 'Ordner',
  'addFolder': 'Ordner hinzufügen',

  'required': 'Erforderlich',
  'invalidEmailAddress': 'Ungültige Emailadresse',
  'wrongPasswordFormat': 'Passwort muss aus mindestens 8 Zeichen, 1 Klein- and 1 Großbuchstabe, 1 Zahl, und 1 Sonderzeichen bestehen',
  'passwordsMustMatch': 'Passwörter müssen übereinstimmen',

  'dashboard': 'Dashboard',

  'rssFeeds': 'RSS Feeds',
  'rssFeeds.feeds': 'Feeds',
  'rssFeeds.renameFolder': 'Ordner umbenennen',
  'rssFeeds.deleteFolder': 'Ordner löschen',
  'rssFeeds.renameFeed': 'Feed umbenennen',
  'rssFeeds.deleteFeed': 'Feed löschen',
  'rssFeeds.areYouSureDeleteFolder': 'Sind Sie sicher, dass Sie diesen Ordner löschen wollen?',
  'rssFeeds.areYouSureDeleteFolderText': 'Alle Feeds in diesem Ordner werden auch gelöscht. Dieser Vorgang kann nicht rückgängig gemacht werden.',
  'rssFeeds.areYouSureDeleteFeed': 'Sind Sie sicher, dass Sie diesen Feed löschen wollen?',
  'rssFeeds.areYouSureDeleteFeedText': 'Dieser Vorgang kann nicht rückgängig gemacht werden.',
  'rssFeeds.folderName': 'Ordnername',
  'rssFeeds.feedName': 'Feedname',
  'rssFeeds.feedUrl': 'Die URL des Feeds',
  'rssFeeds.editFoldersAndFeeds': 'Ordner und Feeds verwalten',
  'rssFeeds.addFeed': 'Feed hinzufügen',
  'rssFeed.noFolder': 'Kein Ordner',

  'account.manageAccount': 'Konto verwalten',
  'account.accountInformation': 'Konto-Informationen',
  'account.updatePassword': 'Passwort aktualisieren',
  'account.sessionManagement': 'Sitzungsverwaltung',
  'account.logOutAllOtherSessions': 'Alle andere Sitzungen abmelden',
  'account.loginDate': 'Anmeldedatum',
  'account.thisSession': 'Diese Sitzung',
  'account.darkMode': 'Dunkelmodus',

  'errors.loginError': 'Anmeldung fehlgeschlagen. Bitte prüfen Sie Ihren Benutzernamen und Ihr Passwort.',
  'errors.registrationError': 'Registrierung fehlgeschlagen. Ein Fehler ist bei der Registrierung Ihres Kontos aufgetreten. Bitte versuchen Sie es später noch einmal.',
  'errors.usernameAlreadyExists': 'Ein Benutzer mit dem angegebenen Benutzernamen existiert bereits. Bitte wählen Sie einen anderen aus.',
  'errors.requiredFieldsMissing': 'Bitte füllen Sie alle erforderlichen Felder aus.',
  'errors.oldPasswordIncorrect': 'Ihr Passwort konnte nicht geändert werden, da das von Ihnen eingegebene aktuelle Passwort ist falsch.',
  'errors.anErrorOccurred': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es später noch einmal.'
};
