export default {
  'loading': 'Loading',

  'firstName': 'First Name',
  'lastName': 'Last Name',
  'emailAddress': 'Email Address',
  'username': 'Username',
  'password': 'Password',
  'currentPassword': 'Current Password',
  'newPassword': 'New Password',
  'passwordRepeat': 'Repeat Password',
  'logIn': 'Log In',
  'logOut': 'Log Out',
  'register': 'Register',
  'save': 'Save',
  'cancel': 'Cancel',
  'close': 'Close',
  'yes': 'Yes',
  'no': 'No',

  'allItems': 'All Items',
  'unreadItems': 'Unread Items',
  'showUnread': 'Show Unread',
  'archive': 'Archive',
  'folder': 'Folder',
  'addFolder': 'Add Folder',

  'required': 'Required',
  'invalidEmailAddress': 'Invalid Email Address',
  'wrongPasswordFormat': 'Password must contain at least 8 characters, 1 lowercase and 1 uppercase letter, 1 number, and 1 symbol',
  'passwordsMustMatch': 'Passwords must match',

  'dashboard': 'Dashboard',

  'rssFeeds': 'RSS Feeds',
  'rssFeeds.feeds': 'Feeds',
  'rssFeeds.renameFolder': 'Rename Folder',
  'rssFeeds.deleteFolder': 'Delete Folder',
  'rssFeeds.areYouSureDeleteFolder': 'Are you sure you want to delete this folder?',
  'rssFeeds.areYouSureDeleteFolderText': 'All feeds in the folder will also be deleted. This action cannot be undone.',
  'rssFeeds.renameFeed': 'Rename Feed',
  'rssFeeds.deleteFeed': 'Delete Feed',
  'rssFeeds.areYouSureDeleteFeed': 'Are you sure you want to delete this feed?',
  'rssFeeds.areYouSureDeleteFeedText': 'This action cannot be undone.',
  'rssFeeds.folderName': 'Folder Name',
  'rssFeeds.feedName': 'Feed Name',
  'rssFeeds.feedUrl': 'Feed URL',
  'rssFeeds.linkToWebsite': 'Link to Website',
  'rssFeeds.editFoldersAndFeeds': 'Edit Folders and Feeds',
  'rssFeeds.addFeed': 'Add Feed',
  'rssFeed.noFolder': 'No Folder',
  'rssFeed.errors.invalidFeedUrl': 'Could not parse the feed URL! Please check to make sure it is a valid feed URL.',
  'rssFeeds.areYouSureMarkAllRead': 'Are you sure you want to mark all articles as read?',
  'rssFeeds.areYouSureMarkAllReadText': 'This action cannot be undone.',
  'rssFeeds.openArticle': 'Open Article',
  'rssFeeds.markAsRead': 'Mark as Read',
  'rssFeeds.markAsUnread': 'Mark as Unread',

  'account.manageAccount': 'Manage Account',
  'account.accountInformation': 'Account Information',
  'account.updatePassword': 'Update Password',
  'account.sessionManagement': 'Session Management',
  'account.logOutAllOtherSessions': 'Log Out All Other Sessions',
  'account.loginDate': 'Login Date',
  'account.thisSession': 'This Session',
  'account.darkMode': 'Dark Mode',

  'errors.loginError': 'Login failed. Please check your username and password.',
  'errors.registrationError': 'Registration failed. An error occurred while trying to register your account. Please try again later.',
  'errors.usernameAlreadyExists': 'A user with this username already exists. Please choose a different one.',
  'errors.requiredFieldsMissing': 'Please fill out all required fields.',
  'errors.oldPasswordIncorrect': 'Your password could not be changed because the current password you entered is incorrect.',
  'errors.anErrorOccurred': 'An error occurred. Please try again later.'
};
